// AI-enhanced (RAG) feedback: rewrites, skill-gap explanations and citations,
// or a clear notice plus the retrieved guidance when the AI layer is unavailable.
import { createContext, useContext, useState } from 'react'
import Icon from './Icon.jsx'
import { Card, Skeleton } from './ui.jsx'

// Lets a citation anywhere in the panel open the retrieved list and jump to its chunk.
const RevealContext = createContext(() => {})

export default function AiFeedbackPanel({ analysis, loading }) {
  const [contextOpen, setContextOpen] = useState(false)
  const reveal = (id) => {
    setContextOpen(true)
    requestAnimationFrame(() => {
      const target = document.getElementById(`chunk-${id}`)
      target?.scrollIntoView({ behavior: 'smooth', block: 'center' })
      target?.focus({ preventScroll: true })
    })
  }
  if (loading) {
    return (
      <Card title="AI-enhanced feedback" subtitle="Retrieving guidance and generating suggestions...">
        <div className="space-y-3" aria-busy="true"><Skeleton className="h-5 w-2/3" /><Skeleton className="h-16" /><Skeleton className="h-16" /></div>
      </Card>
    )
  }
  if (!analysis) return null
  const generated = analysis.generated_feedback
  const context = analysis.retrieved_context || []

  return (
    <RevealContext.Provider value={reveal}>
    <Card title="AI-enhanced feedback"
      subtitle={generated ? `Generated by ${generated.model}, grounded only in the cited knowledge-base chunks` : 'Rule-based results are shown above'}>
      {!analysis.ai_available && (
        <div role="status" className="mb-4 flex items-start gap-3 rounded-xl border border-line bg-card-2 p-3.5 text-sm">
          <Icon name="info" className="mt-0.5 size-5 shrink-0 text-accent-ink" />
          <div>
            <p className="font-medium text-ink">AI suggestions are unavailable right now</p>
            <p className="mt-0.5 text-ink-2">{analysis.ai_unavailable_reason}. Your score and rule-based feedback are unaffected.</p>
          </div>
        </div>
      )}

      {generated && (
        <div className="space-y-6">
          {generated.summary && (
            <p className="rounded-xl bg-accent/10 p-4 text-sm leading-relaxed text-ink">
              {generated.summary.text} <Citations ids={generated.summary.chunk_ids} />
            </p>
          )}
          {generated.bullet_rewrites.length > 0 && (
            <section>
              <h3 className="mb-2 text-sm font-semibold text-ink">Bullet rewrites</h3>
              <ul className="space-y-3">
                {generated.bullet_rewrites.map((r) => (
                  <li key={r.original} className="rounded-xl border border-line p-3.5 text-sm">
                    <p className="text-ink-3"><span className="font-medium text-ink-2">Before: </span>{r.original}</p>
                    <p className="mt-1.5 text-ink"><span className="font-medium text-good-ink">After: </span>{r.rewritten}</p>
                    <p className="mt-1.5"><Citations ids={r.chunk_ids} /></p>
                  </li>
                ))}
              </ul>
              <p className="mt-2 text-xs text-ink-3">Placeholders like [X%] mark numbers only you know. Fill them in with real figures.</p>
            </section>
          )}
          {generated.skill_gaps.length > 0 && (
            <section>
              <h3 className="mb-2 text-sm font-semibold text-ink">Skill gaps explained</h3>
              <ul className="space-y-2">
                {generated.skill_gaps.map((g) => (
                  <li key={g.skill} className="rounded-xl border border-line p-3.5 text-sm">
                    <p className="font-medium text-ink">{g.skill}</p>
                    <p className="mt-1 text-ink-2">{g.explanation} <Citations ids={g.chunk_ids} /></p>
                  </li>
                ))}
              </ul>
            </section>
          )}
          {generated.dropped_items > 0 && (
            <p className="text-xs text-ink-3">{generated.dropped_items} generated item(s) were discarded because they were not properly grounded.</p>
          )}
        </div>
      )}

      {context.length > 0 && (
        <RetrievedContext chunks={context} cited={new Set(generated?.citations || [])}
          open={contextOpen} onToggle={() => setContextOpen((v) => !v)} />
      )}
    </Card>
    </RevealContext.Provider>
  )
}

function Citations({ ids }) {
  const reveal = useContext(RevealContext)
  return (
    <span className="inline-flex flex-wrap gap-1 align-middle">
      {ids.map((id) => (
        <a key={id} href={`#chunk-${id}`} onClick={(e) => { e.preventDefault(); reveal(id) }}
          aria-label={`Source ${id}`} className="focus-ring rounded bg-card-2 px-1.5 py-0.5 font-mono text-[11px] text-accent-ink hover:underline">
          {id}
        </a>
      ))}
    </span>
  )
}

function RetrievedContext({ chunks, cited, open, onToggle }) {
  return (
    <section className="mt-6 border-t border-line pt-4">
      <button type="button" onClick={onToggle} aria-expanded={open} aria-controls="retrieved-context"
        className="focus-ring flex w-full items-center justify-between rounded-lg text-left">
        <span className="inline-flex items-center gap-2 text-sm font-semibold text-ink">
          <Icon name="book" className="size-4 text-ink-3" /> Retrieved guidance ({chunks.length} chunks)
        </span>
        <Icon name="chevron" className={`size-4 text-ink-3 transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>
      <ul id="retrieved-context" hidden={!open} className="mt-3 space-y-2">
        {chunks.map((c) => (
          <li key={c.id} id={`chunk-${c.id}`} tabIndex={-1} className={`scroll-mt-24 rounded-xl border p-3.5 text-sm ${cited.has(c.id) ? 'border-accent/60' : 'border-line'}`}>
            <p className="flex flex-wrap items-center gap-2">
              <span className="font-mono text-xs text-accent-ink">{c.id}</span>
              <span className="font-medium text-ink">{c.title}</span>
              {cited.has(c.id) && <span className="text-xs text-ink-3">cited</span>}
            </p>
            <p className="mt-1 text-ink-2">{c.text}</p>
            <p className="mt-1 text-xs text-ink-3">Source: {c.source} · relevance {c.score.toFixed(2)}</p>
          </li>
        ))}
      </ul>
    </section>
  )
}
